apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-azure-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      volumes:
      - name: myservercontent
        persistentVolumeClaim:
          claimname: pvc-azure #-managed-premium
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - name: myservercontent
          mountPath: "/usr/share/nginx/html/web-app"